spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uploadplatform
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    com.uploadplatform: DEBUG
    org.hibernate.SQL: DEBUG
